#!/usr/bin/env bash

APP="bot_hub"

BUILD_HOST="bothub.colharris.com"
BUILD_USER="root"
BUILD_AT="/git/bothub/apps/bot_hub/builds"
RELEASE_DIR="/git/bothub/apps/bot_hub/builds/rel/bot_hub"
RELEASE_VERSION=0.0.1

STAGING_HOSTS="bothub.colharris.com"
STAGING_USER="git"
TEST_AT="/test/bot_hub"

PRODUCTION_HOSTS="bothub.colharris.com"
PRODUCTION_USER="root"
DELIVER_TO="/opt/bot_hub"
